In [5]:
import pandas as pd
import numpy as np
import os
import re
import json as js
from pathlib import Path
from tqdm import tqdm
from ast import literal_eval

In [6]:
POS = ["v","a","n","pron","adv","num","p"]

def check_pos(data):
    cnt = 0
    
    for i in range(len(data)):
        dt = data[i]
        
        if dt[0] in POS:
            if i != 0:
                cnt += 1
            
    if cnt == 0:
        return False
    elif cnt > 1:
        return False
    else:
        return True


def categorize_anomali_entry(entry_font_size_pos, is_prakategorial):
    output = []
    
    for i in range(len(is_prakategorial)):
        padanan_lema = is_prakategorial[i]
        
        if padanan_lema == 1:
            
            if i == len(is_prakategorial)-1 :
                output.append(1)
            
            elif is_prakategorial[i+1] == 1:
                output.append(1)
            
            elif is_prakategorial[i+1] == 0 and not check_pos(entry_font_size_pos[i+1]):
                output.append(1)
            
            else:
                output.append(0)
                
        else:
            if not check_pos(entry_font_size_pos[i]):
                output.append(1)
            else:
                output.append(0)
    
    return output

In [7]:
directory_CSV = "../Ekstraksi/3. Preprocessing - Replace Kata Singkatan"
directory_hasil = "../Ekstraksi/4. Preprocessing - Remove Anomali Entri"

for filename in tqdm(os.listdir(directory_CSV)):
    print("====" + filename + "====")
    kamus = pd.read_csv(directory_CSV + "/" + filename)
    
    entry_font_size_pos = []
    for i in kamus["entry_font_size_pos"].values.tolist():
        entry_font_size_pos.append(eval(i))
            
    is_prakategorial = kamus["is_padanan_lema"].values.tolist()
            
    kategori_anomali = categorize_anomali_entry(entry_font_size_pos, is_prakategorial)
    kamus["is_anomali"] = kategori_anomali
    
    new_filename = os.path.splitext(filename)[0]
    kamus.to_csv(directory_hasil + "/" + new_filename + "-categorizeAnomali.csv",index=False)
    
#     input_fonts = data["font"].values.tolist()
    
#     if is_contain_bold_and_italic(input_fonts):
#         print("====" + new_filename + "====")
#         CSV_res = build_corpus_one_entry_by_font_pos(data)

#         result_csv = pd.DataFrame.from_dict(CSV_res)
#         result_csv = result_csv[result_csv["Entri"] != ""]
#         result_csv = result_csv.reset_index(drop=True)
#         result_csv.to_csv(directory_hasil + "/" + new_filename + "-one_entry_from_JSON_font_posisi.csv",index=False)
#         try:
#             CSV_res = build_corpus_one_entry_by_font_pos(data)

#             result_csv = pd.DataFrame.from_dict(CSV_res)
#             result_csv.to_csv(directory_hasil + "/" + new_filename + "-one_entry_from_JSON_font_posisi.csv",index=False)
#         except:
#             print("==== Kamus Gagal ====")
#             print(new_filename)

  0%|          | 0/60 [00:00<?, ?it/s]

====10_Replace.csv====

  2%|▏         | 1/60 [00:01<01:32,  1.56s/it]

====11_Replace.csv====

  3%|▎         | 2/60 [00:03<01:28,  1.52s/it]

====12_Replace.csv====

  5%|▌         | 3/60 [00:06<02:11,  2.31s/it]

====13_Replace.csv====

  7%|▋         | 4/60 [00:07<01:50,  1.97s/it]

====14_Replace.csv====

  8%|▊         | 5/60 [00:09<01:50,  2.00s/it]

====15_Replace.csv====

 10%|█         | 6/60 [00:11<01:45,  1.95s/it]

====16_Replace.csv====

 12%|█▏        | 7/60 [00:14<01:50,  2.08s/it]

====17_Replace.csv====

 13%|█▎        | 8/60 [00:15<01:30,  1.74s/it]

====18_Replace.csv====

 15%|█▌        | 9/60 [00:17<01:33,  1.83s/it]

====19_Replace.csv====

 17%|█▋        | 10/60 [00:19<01:46,  2.13s/it]

====20_Replace.csv====

 18%|█▊        | 11/60 [00:20<01:25,  1.75s/it]

====21_Replace.csv====

 20%|██        | 12/60 [00:21<01:13,  1.54s/it]

====22_Replace.csv====

 22%|██▏       | 13/60 [00:24<01:26,  1.85s/it]

====23_Replace.csv====

 23%|██▎       | 14/60 [00:25<01:14,  1.62s/it]

====24_Replace.csv====

 25%|██▌       | 15/60 [00:27<01:20,  1.79s/it]

====25_Replace.csv====

 27%|██▋       | 16/60 [00:29<01:21,  1.84s/it]

====26_Replace.csv====

 28%|██▊       | 17/60 [00:30<01:05,  1.52s/it]

====27_Replace.csv====

 30%|███       | 18/60 [00:31<00:55,  1.32s/it]

====28_Replace.csv====

 32%|███▏      | 19/60 [00:32<00:57,  1.40s/it]

====29_Replace.csv====

 33%|███▎      | 20/60 [00:33<00:50,  1.27s/it]

====2_Replace.csv====

 35%|███▌      | 21/60 [00:35<00:55,  1.43s/it]

====31_Replace.csv====

 37%|███▋      | 22/60 [00:36<00:50,  1.34s/it]

====32_Replace.csv====

 38%|███▊      | 23/60 [00:37<00:47,  1.30s/it]

====33_Replace.csv====

 40%|████      | 24/60 [00:39<00:46,  1.28s/it]

====34_Replace.csv====

 42%|████▏     | 25/60 [00:41<00:56,  1.63s/it]

====36_Replace.csv====

 43%|████▎     | 26/60 [00:42<00:52,  1.54s/it]

====37_Replace.csv====

 45%|████▌     | 27/60 [00:44<00:49,  1.50s/it]

====38_Replace.csv====

 47%|████▋     | 28/60 [00:47<01:03,  1.99s/it]

====3_Replace.csv====

 48%|████▊     | 29/60 [00:50<01:08,  2.20s/it]

====41_Replace.csv====

 50%|█████     | 30/60 [00:52<01:07,  2.26s/it]

====42_Replace.csv====

 52%|█████▏    | 31/60 [00:55<01:10,  2.43s/it]

====44_Replace.csv====

 53%|█████▎    | 32/60 [00:56<00:54,  1.95s/it]

====46_Replace.csv====

 55%|█████▌    | 33/60 [01:00<01:09,  2.56s/it]

====48_Replace.csv====

 57%|█████▋    | 34/60 [01:00<00:52,  2.01s/it]

====4_Replace.csv====

 58%|█████▊    | 35/60 [01:02<00:45,  1.81s/it]

====50_Replace.csv====

 60%|██████    | 36/60 [01:03<00:35,  1.49s/it]

====51_Replace.csv====

 62%|██████▏   | 37/60 [01:03<00:29,  1.27s/it]

====52_Replace.csv====

 63%|██████▎   | 38/60 [01:05<00:30,  1.37s/it]

====54_Replace.csv====

 65%|██████▌   | 39/60 [01:05<00:23,  1.14s/it]

====55_Replace.csv====

 67%|██████▋   | 40/60 [01:07<00:23,  1.17s/it]

====56_Replace.csv====

 68%|██████▊   | 41/60 [01:09<00:27,  1.45s/it]

====58_Replace.csv====

 70%|███████   | 42/60 [01:10<00:24,  1.35s/it]

====5_Replace.csv====

 72%|███████▏  | 43/60 [01:11<00:19,  1.16s/it]

====60_Replace.csv====

 73%|███████▎  | 44/60 [01:13<00:23,  1.48s/it]

====63_Replace.csv====

 75%|███████▌  | 45/60 [01:14<00:21,  1.41s/it]

====66_Replace.csv====

 77%|███████▋  | 46/60 [01:15<00:17,  1.23s/it]

====67_Replace.csv====

 78%|███████▊  | 47/60 [01:17<00:20,  1.61s/it]

====68_Replace.csv====

 80%|████████  | 48/60 [01:19<00:19,  1.61s/it]

====70_Replace.csv====

 82%|████████▏ | 49/60 [01:19<00:13,  1.20s/it]

====71_Replace.csv====

 83%|████████▎ | 50/60 [01:20<00:09,  1.09it/s]

====78_Replace.csv====

 85%|████████▌ | 51/60 [01:20<00:07,  1.17it/s]

====79_Replace.csv====

 87%|████████▋ | 52/60 [01:22<00:08,  1.04s/it]

====84_Replace.csv====

 88%|████████▊ | 53/60 [01:22<00:05,  1.21it/s]

====85_Replace.csv====

 90%|█████████ | 54/60 [01:24<00:06,  1.02s/it]

====87_Replace.csv====

 92%|█████████▏| 55/60 [01:26<00:06,  1.37s/it]

====89_Replace.csv====

 93%|█████████▎| 56/60 [01:26<00:04,  1.06s/it]

====8_Replace.csv====

 95%|█████████▌| 57/60 [01:27<00:02,  1.11it/s]

====91_Replace.csv====

 97%|█████████▋| 58/60 [01:29<00:02,  1.34s/it]

====94_Replace.csv====

 98%|█████████▊| 59/60 [01:30<00:01,  1.28s/it]

====9_Replace.csv====

100%|██████████| 60/60 [01:31<00:00,  1.53s/it]

In [8]:
directory_hasil = "../Ekstraksi/4. Preprocessing - Remove Anomali Entri"

result = {
    "nama_kamus" : [],
    "persentasi_anomali":[],
    "jumlah_entri":[]
}

for filename in tqdm(os.listdir(directory_hasil)):
    print("====" + filename + "====")
    kamus = pd.read_csv(directory_hasil + "/" + filename)
    
    entri = kamus["Entri"].values.tolist()
    anomali = kamus["Entri"][kamus["is_anomali"]==1].values.tolist()
    persen_anomali = round((len(anomali)/len(entri))*100,2)
    
    result['nama_kamus'].append(filename)
    result['persentasi_anomali'].append(persen_anomali)
    result['jumlah_entri'].append(len(entri))
    

res_pandas = pd.DataFrame.from_dict(result)
res_pandas.to_csv("../csvAnalysis/exploratory_anomali.csv",index=False)
    
#     input_fonts = data["font"].values.tolist()
    
#     if is_contain_bold_and_italic(input_fonts):
#         print("====" + new_filename + "====")
#         CSV_res = build_corpus_one_entry_by_font_pos(data)

#         result_csv = pd.DataFrame.from_dict(CSV_res)
#         result_csv = result_csv[result_csv["Entri"] != ""]
#         result_csv = result_csv.reset_index(drop=True)
#         result_csv.to_csv(directory_hasil + "/" + new_filename + "-one_entry_from_JSON_font_posisi.csv",index=False)
#         try:
#             CSV_res = build_corpus_one_entry_by_font_pos(data)

#             result_csv = pd.DataFrame.from_dict(CSV_res)
#             result_csv.to_csv(directory_hasil + "/" + new_filename + "-one_entry_from_JSON_font_posisi.csv",index=False)
#         except:
#             print("==== Kamus Gagal ====")
#             print(new_filename)

  3%|▎         | 2/60 [00:00<00:04, 14.16it/s]

====10_Replace-categorizeAnomali.csv====
====11_Replace-categorizeAnomali.csv====
====12_Replace-categorizeAnomali.csv====

  7%|▋         | 4/60 [00:00<00:05, 10.93it/s]

====13_Replace-categorizeAnomali.csv====
====14_Replace-categorizeAnomali.csv====
====15_Replace-categorizeAnomali.csv====

 13%|█▎        | 8/60 [00:00<00:04, 11.69it/s]

====16_Replace-categorizeAnomali.csv====
====17_Replace-categorizeAnomali.csv====
====18_Replace-categorizeAnomali.csv====

 17%|█▋        | 10/60 [00:00<00:05,  9.69it/s]

====19_Replace-categorizeAnomali.csv====
====20_Replace-categorizeAnomali.csv====

 20%|██        | 12/60 [00:01<00:04, 11.49it/s]

====21_Replace-categorizeAnomali.csv====
====22_Replace-categorizeAnomali.csv====
====23_Replace-categorizeAnomali.csv====

 23%|██▎       | 14/60 [00:01<00:03, 11.98it/s]

====24_Replace-categorizeAnomali.csv====
====25_Replace-categorizeAnomali.csv====

 30%|███       | 18/60 [00:01<00:03, 12.18it/s]

====26_Replace-categorizeAnomali.csv====
====27_Replace-categorizeAnomali.csv====
====28_Replace-categorizeAnomali.csv====
====29_Replace-categorizeAnomali.csv====

 37%|███▋      | 22/60 [00:01<00:02, 13.40it/s]

====2_Replace-categorizeAnomali.csv====
====31_Replace-categorizeAnomali.csv====
====32_Replace-categorizeAnomali.csv====
====33_Replace-categorizeAnomali.csv====

 43%|████▎     | 26/60 [00:02<00:02, 11.65it/s]

====34_Replace-categorizeAnomali.csv====
====36_Replace-categorizeAnomali.csv====
====37_Replace-categorizeAnomali.csv====

 47%|████▋     | 28/60 [00:02<00:02, 11.28it/s]

====38_Replace-categorizeAnomali.csv====
====3_Replace-categorizeAnomali.csv====

 50%|█████     | 30/60 [00:02<00:02, 10.26it/s]

====41_Replace-categorizeAnomali.csv====
====42_Replace-categorizeAnomali.csv====

 53%|█████▎    | 32/60 [00:02<00:02, 10.11it/s]

====44_Replace-categorizeAnomali.csv====
====46_Replace-categorizeAnomali.csv====

 60%|██████    | 36/60 [00:03<00:02, 10.64it/s]

====48_Replace-categorizeAnomali.csv====
====4_Replace-categorizeAnomali.csv====
====50_Replace-categorizeAnomali.csv====
====51_Replace-categorizeAnomali.csv====
====52_Replace-categorizeAnomali.csv====

 67%|██████▋   | 40/60 [00:03<00:01, 12.77it/s]

====54_Replace-categorizeAnomali.csv====
====55_Replace-categorizeAnomali.csv====
====56_Replace-categorizeAnomali.csv====

 70%|███████   | 42/60 [00:03<00:01, 12.51it/s]

====58_Replace-categorizeAnomali.csv====
====5_Replace-categorizeAnomali.csv====
====60_Replace-categorizeAnomali.csv====

 77%|███████▋  | 46/60 [00:04<00:01, 11.75it/s]

====63_Replace-categorizeAnomali.csv====
====66_Replace-categorizeAnomali.csv====
====67_Replace-categorizeAnomali.csv====

 80%|████████  | 48/60 [00:04<00:01,  9.95it/s]

====68_Replace-categorizeAnomali.csv====
====70_Replace-categorizeAnomali.csv====
====71_Replace-categorizeAnomali.csv====
====78_Replace-categorizeAnomali.csv====
====79_Replace-categorizeAnomali.csv====

 87%|████████▋ | 52/60 [00:04<00:00, 14.01it/s]

====84_Replace-categorizeAnomali.csv====
====85_Replace-categorizeAnomali.csv====
====87_Replace-categorizeAnomali.csv====

 92%|█████████▏| 55/60 [00:04<00:00, 12.86it/s]

====89_Replace-categorizeAnomali.csv====
====8_Replace-categorizeAnomali.csv====
====91_Replace-categorizeAnomali.csv====

100%|██████████| 60/60 [00:05<00:00, 11.93it/s]

====94_Replace-categorizeAnomali.csv====
====9_Replace-categorizeAnomali.csv====

In [9]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../csvAnalysis/exploratory_anomali.csv")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
0   10_Replace-categorizeAnomali.csv               27.12          5287
1   11_Replace-categorizeAnomali.csv               81.16          2298
2   12_Replace-categorizeAnomali.csv               33.20          9411
3   13_Replace-categorizeAnomali.csv               69.66          1025
4   14_Replace-categorizeAnomali.csv               61.61          1258
5   15_Replace-categorizeAnomali.csv               70.53          1500
6   16_Replace-categorizeAnomali.csv               52.17          4108
7   17_Replace-categorizeAnomali.csv               98.15          2161
8   18_Replace-categorizeAnomali.csv               32.96         14890
9   19_Replace-categorizeAnomali.csv               36.70          8562
10  20_Replace-categorizeAnomali.csv               99.81          2109
11  21_Replace-categorizeAnomali.csv               48.28          2997
12  22_Replace-categorizeAnomali.csv               96.72           366
13  23_Replace-categorizeAnomali.csv               35.87          2938
14  24_Replace-categorizeAnomali.csv               46.42          8517
15  25_Replace-categorizeAnomali.csv               61.82           440
16  26_Replace-categorizeAnomali.csv               35.42          4743
17  27_Replace-categorizeAnomali.csv               56.84          3728
18  28_Replace-categorizeAnomali.csv               38.17          1082
19  29_Replace-categorizeAnomali.csv               99.75          1980
20   2_Replace-categorizeAnomali.csv               97.81          4752
21  31_Replace-categorizeAnomali.csv               99.12          1371
22  32_Replace-categorizeAnomali.csv               99.23          3365
23  33_Replace-categorizeAnomali.csv               90.14          2912
24  34_Replace-categorizeAnomali.csv               47.98         11225
25  36_Replace-categorizeAnomali.csv               48.39          2792
26  37_Replace-categorizeAnomali.csv               70.91           361
27  38_Replace-categorizeAnomali.csv               94.28          4372
28   3_Replace-categorizeAnomali.csv               96.52           834
29  41_Replace-categorizeAnomali.csv               40.44         13390
30  42_Replace-categorizeAnomali.csv               50.64          6931
31  44_Replace-categorizeAnomali.csv               98.85          2002
32  46_Replace-categorizeAnomali.csv               34.13         13239
33  48_Replace-categorizeAnomali.csv               94.42           233
34   4_Replace-categorizeAnomali.csv               37.10          3213
35  50_Replace-categorizeAnomali.csv               73.33          1620
36  51_Replace-categorizeAnomali.csv               82.82          2095
37  52_Replace-categorizeAnomali.csv               99.03          2682
38  54_Replace-categorizeAnomali.csv               53.78          2356
39  55_Replace-categorizeAnomali.csv               42.62          2668
40  56_Replace-categorizeAnomali.csv               98.85          3119
41  58_Replace-categorizeAnomali.csv               98.82          5255
42   5_Replace-categorizeAnomali.csv               37.96          3854
43  60_Replace-categorizeAnomali.csv               86.56          1644
44  63_Replace-categorizeAnomali.csv               65.81          1085
45  66_Replace-categorizeAnomali.csv               99.10          1661
46  67_Replace-categorizeAnomali.csv               94.10          3135
47  68_Replace-categorizeAnomali.csv                8.04          7546
48  70_Replace-categorizeAnomali.csv               55.08           354
49  71_Replace-categorizeAnomali.csv               12.83           904
50  78_Replace-categorizeAnomali.csv               99.16          1196
51  79_Replace-categorizeAnomali.csv               59.40          1877
52  84_Replace-categorizeAnomali.csv               99.10          1001
53  85_Replace-categorizeAnomali.csv               94.93          1243
54  87_Replace-categorizeAnomali.csv               66.48          2315
55  89_Replace-categorizeAnomali.csv                2.17          1153
56   8_Replace-categorizeAnomali.csv               84.75          2282
57  91_Replace-categorizeAnomali.csv                7.91         10852
58  94_Replace-categorizeAnomali.csv               94.36           958
59   9_Replace-categorizeAnomali.csv               97.29          2248

In [10]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] > 50]
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
1   11_Replace-categorizeAnomali.csv               81.16          2298
3   13_Replace-categorizeAnomali.csv               69.66          1025
4   14_Replace-categorizeAnomali.csv               61.61          1258
5   15_Replace-categorizeAnomali.csv               70.53          1500
6   16_Replace-categorizeAnomali.csv               52.17          4108
7   17_Replace-categorizeAnomali.csv               98.15          2161
10  20_Replace-categorizeAnomali.csv               99.81          2109
12  22_Replace-categorizeAnomali.csv               96.72           366
15  25_Replace-categorizeAnomali.csv               61.82           440
17  27_Replace-categorizeAnomali.csv               56.84          3728
19  29_Replace-categorizeAnomali.csv               99.75          1980
20   2_Replace-categorizeAnomali.csv               97.81          4752
21  31_Replace-categorizeAnomali.csv               99.12          1371
22  32_Replace-categorizeAnomali.csv               99.23          3365
23  33_Replace-categorizeAnomali.csv               90.14          2912
26  37_Replace-categorizeAnomali.csv               70.91           361
27  38_Replace-categorizeAnomali.csv               94.28          4372
28   3_Replace-categorizeAnomali.csv               96.52           834
30  42_Replace-categorizeAnomali.csv               50.64          6931
31  44_Replace-categorizeAnomali.csv               98.85          2002
33  48_Replace-categorizeAnomali.csv               94.42           233
35  50_Replace-categorizeAnomali.csv               73.33          1620
36  51_Replace-categorizeAnomali.csv               82.82          2095
37  52_Replace-categorizeAnomali.csv               99.03          2682
38  54_Replace-categorizeAnomali.csv               53.78          2356
40  56_Replace-categorizeAnomali.csv               98.85          3119
41  58_Replace-categorizeAnomali.csv               98.82          5255
43  60_Replace-categorizeAnomali.csv               86.56          1644
44  63_Replace-categorizeAnomali.csv               65.81          1085
45  66_Replace-categorizeAnomali.csv               99.10          1661
46  67_Replace-categorizeAnomali.csv               94.10          3135
48  70_Replace-categorizeAnomali.csv               55.08           354
50  78_Replace-categorizeAnomali.csv               99.16          1196
51  79_Replace-categorizeAnomali.csv               59.40          1877
52  84_Replace-categorizeAnomali.csv               99.10          1001
53  85_Replace-categorizeAnomali.csv               94.93          1243
54  87_Replace-categorizeAnomali.csv               66.48          2315
56   8_Replace-categorizeAnomali.csv               84.75          2282
58  94_Replace-categorizeAnomali.csv               94.36           958
59   9_Replace-categorizeAnomali.csv               97.29          2248

(40, 3)

In [11]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] < 90]
data = data[data["persentasi_anomali"] > 50]
data = data.sort_values(by=["persentasi_anomali"], ascending=False) 
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")
data.to_csv("top5090%.csv",index=False)

                          nama_kamus  persentasi_anomali  jumlah_entri
43  60_Replace-categorizeAnomali.csv               86.56          1644
56   8_Replace-categorizeAnomali.csv               84.75          2282
36  51_Replace-categorizeAnomali.csv               82.82          2095
1   11_Replace-categorizeAnomali.csv               81.16          2298
35  50_Replace-categorizeAnomali.csv               73.33          1620
26  37_Replace-categorizeAnomali.csv               70.91           361
5   15_Replace-categorizeAnomali.csv               70.53          1500
3   13_Replace-categorizeAnomali.csv               69.66          1025
54  87_Replace-categorizeAnomali.csv               66.48          2315
44  63_Replace-categorizeAnomali.csv               65.81          1085
15  25_Replace-categorizeAnomali.csv               61.82           440
4   14_Replace-categorizeAnomali.csv               61.61          1258
51  79_Replace-categorizeAnomali.csv               59.40          1877
17  27_Replace-categorizeAnomali.csv               56.84          3728
48  70_Replace-categorizeAnomali.csv               55.08           354
38  54_Replace-categorizeAnomali.csv               53.78          2356
6   16_Replace-categorizeAnomali.csv               52.17          4108
30  42_Replace-categorizeAnomali.csv               50.64          6931

(18, 3)

In [12]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] > 90]
data = data.sort_values(by=["persentasi_anomali"], ascending=False)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")
data.to_csv("top90%.csv",index=False)

                          nama_kamus  persentasi_anomali  jumlah_entri
10  20_Replace-categorizeAnomali.csv               99.81          2109
19  29_Replace-categorizeAnomali.csv               99.75          1980
22  32_Replace-categorizeAnomali.csv               99.23          3365
50  78_Replace-categorizeAnomali.csv               99.16          1196
21  31_Replace-categorizeAnomali.csv               99.12          1371
45  66_Replace-categorizeAnomali.csv               99.10          1661
52  84_Replace-categorizeAnomali.csv               99.10          1001
37  52_Replace-categorizeAnomali.csv               99.03          2682
40  56_Replace-categorizeAnomali.csv               98.85          3119
31  44_Replace-categorizeAnomali.csv               98.85          2002
41  58_Replace-categorizeAnomali.csv               98.82          5255
7   17_Replace-categorizeAnomali.csv               98.15          2161
20   2_Replace-categorizeAnomali.csv               97.81          4752
59   9_Replace-categorizeAnomali.csv               97.29          2248
12  22_Replace-categorizeAnomali.csv               96.72           366
28   3_Replace-categorizeAnomali.csv               96.52           834
53  85_Replace-categorizeAnomali.csv               94.93          1243
33  48_Replace-categorizeAnomali.csv               94.42           233
58  94_Replace-categorizeAnomali.csv               94.36           958
27  38_Replace-categorizeAnomali.csv               94.28          4372
46  67_Replace-categorizeAnomali.csv               94.10          3135
23  33_Replace-categorizeAnomali.csv               90.14          2912

(22, 3)

In [13]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] > 80]
data = data[data["persentasi_anomali"] <= 90]
data = data.sort_values(by=["persentasi_anomali"], ascending=False)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
43  60_Replace-categorizeAnomali.csv               86.56          1644
56   8_Replace-categorizeAnomali.csv               84.75          2282
36  51_Replace-categorizeAnomali.csv               82.82          2095
1   11_Replace-categorizeAnomali.csv               81.16          2298

(4, 3)

In [14]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../csvAnalysis/exploratory_anomali.csv")
data = data[data["persentasi_anomali"] > 0]
data = data[data["persentasi_anomali"] <= 30]
data = data.sort_values(by=["persentasi_anomali"], ascending=False)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
0   10_Replace-categorizeAnomali.csv               27.12          5287
49  71_Replace-categorizeAnomali.csv               12.83           904
47  68_Replace-categorizeAnomali.csv                8.04          7546
57  91_Replace-categorizeAnomali.csv                7.91         10852
55  89_Replace-categorizeAnomali.csv                2.17          1153

(5, 3)

In [15]:
# tampilkan seluruh baris dan seluruh nilai pada kolom

data = pd.read_csv("../csvAnalysis/exploratory_anomali.csv")
data = data.sort_values(by=["persentasi_anomali"], ascending=False)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(data)
display(data.shape)

# reset option
pd.reset_option("display")

                          nama_kamus  persentasi_anomali  jumlah_entri
10  20_Replace-categorizeAnomali.csv               99.81          2109
19  29_Replace-categorizeAnomali.csv               99.75          1980
22  32_Replace-categorizeAnomali.csv               99.23          3365
50  78_Replace-categorizeAnomali.csv               99.16          1196
21  31_Replace-categorizeAnomali.csv               99.12          1371
45  66_Replace-categorizeAnomali.csv               99.10          1661
52  84_Replace-categorizeAnomali.csv               99.10          1001
37  52_Replace-categorizeAnomali.csv               99.03          2682
31  44_Replace-categorizeAnomali.csv               98.85          2002
40  56_Replace-categorizeAnomali.csv               98.85          3119
41  58_Replace-categorizeAnomali.csv               98.82          5255
7   17_Replace-categorizeAnomali.csv               98.15          2161
20   2_Replace-categorizeAnomali.csv               97.81          4752
59   9_Replace-categorizeAnomali.csv               97.29          2248
12  22_Replace-categorizeAnomali.csv               96.72           366
28   3_Replace-categorizeAnomali.csv               96.52           834
53  85_Replace-categorizeAnomali.csv               94.93          1243
33  48_Replace-categorizeAnomali.csv               94.42           233
58  94_Replace-categorizeAnomali.csv               94.36           958
27  38_Replace-categorizeAnomali.csv               94.28          4372
46  67_Replace-categorizeAnomali.csv               94.10          3135
23  33_Replace-categorizeAnomali.csv               90.14          2912
43  60_Replace-categorizeAnomali.csv               86.56          1644
56   8_Replace-categorizeAnomali.csv               84.75          2282
36  51_Replace-categorizeAnomali.csv               82.82          2095
1   11_Replace-categorizeAnomali.csv               81.16          2298
35  50_Replace-categorizeAnomali.csv               73.33          1620
26  37_Replace-categorizeAnomali.csv               70.91           361
5   15_Replace-categorizeAnomali.csv               70.53          1500
3   13_Replace-categorizeAnomali.csv               69.66          1025
54  87_Replace-categorizeAnomali.csv               66.48          2315
44  63_Replace-categorizeAnomali.csv               65.81          1085
15  25_Replace-categorizeAnomali.csv               61.82           440
4   14_Replace-categorizeAnomali.csv               61.61          1258
51  79_Replace-categorizeAnomali.csv               59.40          1877
17  27_Replace-categorizeAnomali.csv               56.84          3728
48  70_Replace-categorizeAnomali.csv               55.08           354
38  54_Replace-categorizeAnomali.csv               53.78          2356
6   16_Replace-categorizeAnomali.csv               52.17          4108
30  42_Replace-categorizeAnomali.csv               50.64          6931
25  36_Replace-categorizeAnomali.csv               48.39          2792
11  21_Replace-categorizeAnomali.csv               48.28          2997
24  34_Replace-categorizeAnomali.csv               47.98         11225
14  24_Replace-categorizeAnomali.csv               46.42          8517
39  55_Replace-categorizeAnomali.csv               42.62          2668
29  41_Replace-categorizeAnomali.csv               40.44         13390
18  28_Replace-categorizeAnomali.csv               38.17          1082
42   5_Replace-categorizeAnomali.csv               37.96          3854
34   4_Replace-categorizeAnomali.csv               37.10          3213
9   19_Replace-categorizeAnomali.csv               36.70          8562
13  23_Replace-categorizeAnomali.csv               35.87          2938
16  26_Replace-categorizeAnomali.csv               35.42          4743
32  46_Replace-categorizeAnomali.csv               34.13         13239
2   12_Replace-categorizeAnomali.csv               33.20          9411
8   18_Replace-categorizeAnomali.csv               32.96         14890
0   10_Replace-categorizeAnomali.csv               27.12          5287
49  71_Replace-categorizeAnomali.csv               12.83           904
47  68_Replace-categorizeAnomali.csv                8.04          7546
57  91_Replace-categorizeAnomali.csv                7.91         10852
55  89_Replace-categorizeAnomali.csv                2.17          1153

(60, 3)