In [17]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

In [18]:
directory = '../[Full] CSV JSON all information - Final'

In [19]:
def count_font_bold(data):
    cnt = 0
    for i in data:
        if "bold" in i.lower():
            cnt += 1
    return cnt

def count_font_italic(data):
    cnt = 0
    for i in data:
        if "italic" in i.lower():
            cnt += 1
    return cnt

In [20]:
page = [1,1,1,1,2,2,2,2,]

page = np.array(page)
page = np.unique(page)
page[-1]

np.int64(2)

In [21]:
result = {
    "nama_kamus":[],
    "jumlah_bold":[],
    "jumlah_italic":[],
    "mean_ukuran_char":[],
    "banyak_halaman":[]
}

for filename in tqdm(os.listdir(directory)):
    data = pd.read_csv(directory + "/" + filename)
    
    sum_bold = count_font_bold(data["font"].values.tolist())
    sum_italic = count_font_italic(data["font"].values.tolist())
    
    size = data["size"].values.tolist()

    page = np.array(data["page"].values.tolist())
    page = np.unique(page)
    
    result['nama_kamus'].append(filename)
    result['jumlah_bold'].append(sum_bold)
    result['jumlah_italic'].append(sum_italic)
    result['mean_ukuran_char'].append(round(np.mean(size),2))
    result['banyak_halaman'].append(len(page))

100%|██████████| 66/66 [00:07<00:00,  8.66it/s]

In [22]:
pandas_res = pd.DataFrame.from_dict(result)
# tampilkan seluruh baris dan seluruh nilai pada kolom
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(pandas_res)

# reset option
pd.reset_option("display")

pandas_res.to_csv("../csvAnalysis/exploratory_kamus_analysis.csv",index=False)

,nama_kamus,jumlah_bold,jumlah_italic,mean_ukuran_char,banyak_halaman
0,1. Kamus Makasar-Indonesia (1995)-hasil-ekstraksi.csv,4905,17774,11.35,446
1,10. Kamus Bahasa Indonesia-Dayak Deah Edisi I (2013)-hasil-ekstraksi.csv,5634,17598,9.07,300
2,11. Kamus Suwawa-Indonesia (1985)-hasil-ekstraksi.csv,4,34930,9.41,335
3,12. Kamus Bahasa Indonesia-Kaidipang L-Z (2000)-hasil-ekstraksi.csv,12383,28479,11.15,512
4,13. Kamus Bahasa Indonesia-Bahasa Sunda I (1993)-hasil-ekstraksi.csv,317,22602,10.55,408
5,14. Kamus Indonesia-Minangkabau II (1994)-hasil-ekstraksi.csv,606,30562,10.79,465
6,15. Kamus Bahasa Indonesia-Pasir (1997)-hasil-ekstraksi.csv,673,39746,10.74,529
7,16. Kamus Bahasa Indonesia Karo A-K (1998)-hasil-ekstraksi.csv,2257,28938,10.36,401
8,17. Kamus Melayu Makasar-Indonesia (1985)-hasil-ekstraksi.csv,2838,12798,10.21,143
9,18. Kamus Bahasa Jawa-Bahasa Indonesia I (1993)-hasil-ekstraksi.csv,20527,8640,11.11,450
10,19. Kamus Bahasa Indoensia-Melayu Riau (1997)-hasil-ekstraksi.csv,9504,29076,11.55,436
11,2. Kamus Melayu-Indonesia (1985)-hasil-ekstraksi.csv,7563,15196,10.68,229
12,20. Kamus Bahasa Melayu Ambon-Indonesia (1998)-hasil-ekstraksi.csv,2230,12638,11.78,138
13,21. Kamus Bahasa Indonesia-Sentani A-K (1999)-hasil-ekstraksi.csv,5104,14987,11.32,182
14,22. Kamus Bahasa Gorontalo-Indonesia (1977)-hasil-ekstraksi.csv,37,37556,8.42,302
15,23. Kamus Dwibahasa Dayak Ngaju-Indonesia (2013)-hasil-ekstraksi.csv,3581,631,8.98,154
16,24. Kamus Minangkabau-Indonesia (1985)-hasil-ekstraksi.csv,11952,26256,9.92,312
17,25. Kamus Bahasa Indonesia Jambi L-Z (1997)-hasil-ekstraksi.csv,136,32818,11.26,332
18,26. Kamus Bahasa Indonesia-Bahasa Tonsea II (1996)-hasil-ekstraksi.csv,5354,2711,11.09,168
19,27. Kamus Bahasa Indonesia-Saluan (2012)-hasil-ekstraksi.csv,9105,11147,10.10,120
20,28. Kamus Bahasa Kutai-Bahasa Indonesia (2013)-hasil-ekstraksi.csv,819,27928,10.59,436
21,3. Kamus Bahasa Gorontalo-Indonesia (2001)-hasil-ekstraksi.csv,62,37205,8.19,302
22,31. Kamus Sumbawa-Indonesia (1985)-hasil-ekstraksi.csv,483,10553,9.31,167
23,32. Kamus Melayu Langkat-Indonesia (1985)-hasil-ekstraksi.csv,3246,8312,10.05,183
24,33. Kamus Wolio Indonesia (1985)-hasil-ekstraksi.csv,2746,12779,10.27,191
25,34. Kamus Bahasa Indonesia-Bali L-Z (1998)-hasil-ekstraksi.csv,16323,18825,10.76,498
26,35. Kamus Bahasa Indonesia-Bahasa Gayo I (1996)-hasil-ekstraksi.csv,2523,27282,10.22,350
27,36. Kamus Bahasa Indonesia-Kulawi (2012)-hasil-ekstraksi.csv,1443,21190,9.60,222
28,37. Kamus Bahasa Indonesia Bakumpai II (1995)-hasil-ekstraksi.csv,42,22995,10.64,250
29,38. Kamus Bahasa Indonesia-Karo L-Z (1999)-hasil-ekstraksi.csv,2113,30006,10.86,584
30,4. Kamus Bahasa Indonesia-Jambi A-K (1998)-hasil-ekstraksi.csv,4023,23554,11.37,208
31,41. Kamus Bahasa Indonesia-Bali A-K (1997)-hasil-ekstraksi.csv,16876,23898,11.50,451
32,42. Kamus Bahasa Indonesia-Bahasa Sunda II (1993)-hasil-ekstraksi.csv,6365,35806,11.32,486
33,43. Kamus Indonesia-Minangkabau I (1994)-hasil-ekstraksi.csv,5710,35020,11.35,376
34,44. Kamus Melayu Deli-Indonesia (1985)-hasil-ekstraksi.csv,2150,8078,10.20,117
35,45. Kamus Bahasa Indonesia-Bahasa Gayo II (1996)-hasil-ekstraksi.csv,3098,19912,10.18,321
36,46. Kamus Bahasa Banjar Dialek Hulu-Indonesia (2008)-hasil-ekstraksi.csv,26876,36691,8.52,310
37,48. Kamus Muna-Indonesia (1985)-hasil-ekstraksi.csv,124,10311,9.78,140
38,5. Kamus Bahasa Indonesia-Bahasa Tonsea I (1996)-hasil-ekstraksi.csv,4744,2145,11.15,148
39,50. Kamus Indonesia-Jawa Kuno (1992)-hasil-ekstraksi.csv,13,3312,9.59,172
40,51. Kamus Bahasa Bali Kuno-Indonesia (1985)-hasil-ekstraksi.csv,1911,5688,9.95,122
41,52. Kamus Ogan-Indonesia (1985)-hasil-ekstraksi.csv,6643,21366,10.45,249
42,54. Kamus Bahasa Indonesia Mentawai (1998)-hasil-ekstraksi.csv,2521,8181,11.08,91
43,55. Kamus Bahasa Indonesia Bakumpai I (1995)-hasil-ekstraksi.csv,2334,19643,11.29,198
44,56. Kamus Lampung-Indonesia (1985)-hasil-ekstraksi.csv,6144,27041,10.24,305
45,57. Kamus Bahasa Bugis-Indonesia (1977)-hasil-ekstraksi.csv,1843,21145,8.50,211
46,58. Kamus Melayu Ketapang-Indonesia A-M (2010)-hasil-ekstraksi.csv,5849,1723,9.46,159
47,60. Kamus Sunda-Indonesia (1985)-hasil-ekstraksi.csv,480,8381,9.09,382
48,61. Kamus Banjar-Indonesia (1977)-hasil-ekstraksi.csv,10053,6097,9.12,160
49,62. Kamus Umum Kerinci-Indonesia (1985)-hasil-ekstraksi.csv,33036,16705,9.09,328
50,63. Kamus Bahasa Indonesia-Lampung Dialek A (1999)-hasil-ekstraksi.csv,972,13724,10.77,321
51,66. Kamus Melayu Bali-Indonesia (1985)-hasil-ekstraksi.csv,2032,8711,10.21,126
52,67. Kamus Aceh Indonesia (A-L) (1985)-hasil-ekstraksi.csv,112,48446,9.66,560
53,68. Kamus Dwibahasa Talaud - Indonesia (2018)-hasil-ekstraksi.csv,13907,19156,11.02,283
54,71. Kamus dwibahasa Bugis-Indonesia (2017)-hasil-ekstraksi.csv,1201,3623,11.02,49
55,74. Kamus Bahasa Melayu Bangka-Indonesia (2018)-hasil-ekstraksi.csv,3627,0,11.98,156
56,77. Kamus Samawa-Indonesia Edisi 2 (2017)-hasil-ekstraksi.csv,2582,19565,8.70,153
57,78. Kamus Tolaki-Indonesia (1985)-hasil-ekstraksi.csv,179,13280,9.67,160
58,79. Kamus Bahasa Jawa-Bahasa Indonesia II (1993)-hasil-ekstraksi.csv,13,7670,10.89,415
59,8. Kamus Indonesia-Angkola (1995)-hasil-ekstraksi.csv,310,4417,8.80,154
60,84. Kamus Bahasa Biak - Indonesia (1977) -hasil-ekstraksi.csv,1,9565,8.33,79
61,85. Kamus Tondano-Indonesia (1985)-hasil-ekstraksi.csv,1229,16617,9.25,296
62,87. Kamus Bahasa Indonesia-Kaidipang (A-K) (1999)-hasil-ekstraksi.csv,878,30146,10.71,525
63,9. Kamus Manado-Indonesia (1985)-hasil-ekstraksi.csv,8908,10412,9.32,136
64,91. Kamus Simalungun - Indonesia (edisi kedua) (2015)-hasil-ekstraksi.csv,13465,33758,9.98,264
65,94. Kamus Bahasa Madura-Indonesia (1977)-hasil-ekstraksi.csv,126,14027,7.90,208

In [23]:
pandas_res = pd.read_csv("../csvAnalysis/exploratory_kamus_analysis.csv")

pandas_res = pandas_res[(pandas_res["jumlah_bold"] >= pandas_res["banyak_halaman"]) & (pandas_res["jumlah_italic"] >= pandas_res["banyak_halaman"])]
pandas_res = pandas_res.reset_index(drop=True)
# tampilkan seluruh baris dan seluruh nilai pada kolom
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pandas_res.to_csv("../csvAnalysis/daftar_kamus_ekstraks.csv",index=False)

display(pandas_res)

# reset option
pd.reset_option("display")

,nama_kamus,jumlah_bold,jumlah_italic,mean_ukuran_char,banyak_halaman
0,1. Kamus Makasar-Indonesia (1995)-hasil-ekstraksi.csv,4905,17774,11.35,446
1,10. Kamus Bahasa Indonesia-Dayak Deah Edisi I (2013)-hasil-ekstraksi.csv,5634,17598,9.07,300
2,12. Kamus Bahasa Indonesia-Kaidipang L-Z (2000)-hasil-ekstraksi.csv,12383,28479,11.15,512
3,14. Kamus Indonesia-Minangkabau II (1994)-hasil-ekstraksi.csv,606,30562,10.79,465
4,15. Kamus Bahasa Indonesia-Pasir (1997)-hasil-ekstraksi.csv,673,39746,10.74,529
5,16. Kamus Bahasa Indonesia Karo A-K (1998)-hasil-ekstraksi.csv,2257,28938,10.36,401
6,17. Kamus Melayu Makasar-Indonesia (1985)-hasil-ekstraksi.csv,2838,12798,10.21,143
7,18. Kamus Bahasa Jawa-Bahasa Indonesia I (1993)-hasil-ekstraksi.csv,20527,8640,11.11,450
8,19. Kamus Bahasa Indoensia-Melayu Riau (1997)-hasil-ekstraksi.csv,9504,29076,11.55,436
9,2. Kamus Melayu-Indonesia (1985)-hasil-ekstraksi.csv,7563,15196,10.68,229
10,20. Kamus Bahasa Melayu Ambon-Indonesia (1998)-hasil-ekstraksi.csv,2230,12638,11.78,138
11,21. Kamus Bahasa Indonesia-Sentani A-K (1999)-hasil-ekstraksi.csv,5104,14987,11.32,182
12,23. Kamus Dwibahasa Dayak Ngaju-Indonesia (2013)-hasil-ekstraksi.csv,3581,631,8.98,154
13,24. Kamus Minangkabau-Indonesia (1985)-hasil-ekstraksi.csv,11952,26256,9.92,312
14,26. Kamus Bahasa Indonesia-Bahasa Tonsea II (1996)-hasil-ekstraksi.csv,5354,2711,11.09,168
15,27. Kamus Bahasa Indonesia-Saluan (2012)-hasil-ekstraksi.csv,9105,11147,10.10,120
16,28. Kamus Bahasa Kutai-Bahasa Indonesia (2013)-hasil-ekstraksi.csv,819,27928,10.59,436
17,31. Kamus Sumbawa-Indonesia (1985)-hasil-ekstraksi.csv,483,10553,9.31,167
18,32. Kamus Melayu Langkat-Indonesia (1985)-hasil-ekstraksi.csv,3246,8312,10.05,183
19,33. Kamus Wolio Indonesia (1985)-hasil-ekstraksi.csv,2746,12779,10.27,191
20,34. Kamus Bahasa Indonesia-Bali L-Z (1998)-hasil-ekstraksi.csv,16323,18825,10.76,498
21,35. Kamus Bahasa Indonesia-Bahasa Gayo I (1996)-hasil-ekstraksi.csv,2523,27282,10.22,350
22,36. Kamus Bahasa Indonesia-Kulawi (2012)-hasil-ekstraksi.csv,1443,21190,9.60,222
23,38. Kamus Bahasa Indonesia-Karo L-Z (1999)-hasil-ekstraksi.csv,2113,30006,10.86,584
24,4. Kamus Bahasa Indonesia-Jambi A-K (1998)-hasil-ekstraksi.csv,4023,23554,11.37,208
25,41. Kamus Bahasa Indonesia-Bali A-K (1997)-hasil-ekstraksi.csv,16876,23898,11.50,451
26,42. Kamus Bahasa Indonesia-Bahasa Sunda II (1993)-hasil-ekstraksi.csv,6365,35806,11.32,486
27,43. Kamus Indonesia-Minangkabau I (1994)-hasil-ekstraksi.csv,5710,35020,11.35,376
28,44. Kamus Melayu Deli-Indonesia (1985)-hasil-ekstraksi.csv,2150,8078,10.20,117
29,45. Kamus Bahasa Indonesia-Bahasa Gayo II (1996)-hasil-ekstraksi.csv,3098,19912,10.18,321
30,46. Kamus Bahasa Banjar Dialek Hulu-Indonesia (2008)-hasil-ekstraksi.csv,26876,36691,8.52,310
31,5. Kamus Bahasa Indonesia-Bahasa Tonsea I (1996)-hasil-ekstraksi.csv,4744,2145,11.15,148
32,51. Kamus Bahasa Bali Kuno-Indonesia (1985)-hasil-ekstraksi.csv,1911,5688,9.95,122
33,52. Kamus Ogan-Indonesia (1985)-hasil-ekstraksi.csv,6643,21366,10.45,249
34,54. Kamus Bahasa Indonesia Mentawai (1998)-hasil-ekstraksi.csv,2521,8181,11.08,91
35,55. Kamus Bahasa Indonesia Bakumpai I (1995)-hasil-ekstraksi.csv,2334,19643,11.29,198
36,56. Kamus Lampung-Indonesia (1985)-hasil-ekstraksi.csv,6144,27041,10.24,305
37,57. Kamus Bahasa Bugis-Indonesia (1977)-hasil-ekstraksi.csv,1843,21145,8.50,211
38,58. Kamus Melayu Ketapang-Indonesia A-M (2010)-hasil-ekstraksi.csv,5849,1723,9.46,159
39,60. Kamus Sunda-Indonesia (1985)-hasil-ekstraksi.csv,480,8381,9.09,382
40,61. Kamus Banjar-Indonesia (1977)-hasil-ekstraksi.csv,10053,6097,9.12,160
41,62. Kamus Umum Kerinci-Indonesia (1985)-hasil-ekstraksi.csv,33036,16705,9.09,328
42,63. Kamus Bahasa Indonesia-Lampung Dialek A (1999)-hasil-ekstraksi.csv,972,13724,10.77,321
43,66. Kamus Melayu Bali-Indonesia (1985)-hasil-ekstraksi.csv,2032,8711,10.21,126
44,68. Kamus Dwibahasa Talaud - Indonesia (2018)-hasil-ekstraksi.csv,13907,19156,11.02,283
45,71. Kamus dwibahasa Bugis-Indonesia (2017)-hasil-ekstraksi.csv,1201,3623,11.02,49
46,77. Kamus Samawa-Indonesia Edisi 2 (2017)-hasil-ekstraksi.csv,2582,19565,8.70,153
47,78. Kamus Tolaki-Indonesia (1985)-hasil-ekstraksi.csv,179,13280,9.67,160
48,8. Kamus Indonesia-Angkola (1995)-hasil-ekstraksi.csv,310,4417,8.80,154
49,85. Kamus Tondano-Indonesia (1985)-hasil-ekstraksi.csv,1229,16617,9.25,296
50,87. Kamus Bahasa Indonesia-Kaidipang (A-K) (1999)-hasil-ekstraksi.csv,878,30146,10.71,525
51,9. Kamus Manado-Indonesia (1985)-hasil-ekstraksi.csv,8908,10412,9.32,136
52,91. Kamus Simalungun - Indonesia (edisi kedua) (2015)-hasil-ekstraksi.csv,13465,33758,9.98,264

In [24]:
pandas_res = pd.read_csv("../csvAnalysis/exploratory_kamus_analysis.csv")

pandas_res = pandas_res[(pandas_res["jumlah_bold"] < pandas_res["banyak_halaman"]) | (pandas_res["jumlah_italic"] < pandas_res["banyak_halaman"])]
pandas_res = pandas_res.reset_index(drop=True)
# tampilkan seluruh baris dan seluruh nilai pada kolom
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(pandas_res)

# reset option
pd.reset_option("display")
pandas_res.to_csv("../csvAnalysis/daftar kamus yang tidak diekstrak.csv",index=False)

,nama_kamus,jumlah_bold,jumlah_italic,mean_ukuran_char,banyak_halaman
0,11. Kamus Suwawa-Indonesia (1985)-hasil-ekstraksi.csv,4,34930,9.41,335
1,13. Kamus Bahasa Indonesia-Bahasa Sunda I (1993)-hasil-ekstraksi.csv,317,22602,10.55,408
2,22. Kamus Bahasa Gorontalo-Indonesia (1977)-hasil-ekstraksi.csv,37,37556,8.42,302
3,25. Kamus Bahasa Indonesia Jambi L-Z (1997)-hasil-ekstraksi.csv,136,32818,11.26,332
4,3. Kamus Bahasa Gorontalo-Indonesia (2001)-hasil-ekstraksi.csv,62,37205,8.19,302
5,37. Kamus Bahasa Indonesia Bakumpai II (1995)-hasil-ekstraksi.csv,42,22995,10.64,250
6,48. Kamus Muna-Indonesia (1985)-hasil-ekstraksi.csv,124,10311,9.78,140
7,50. Kamus Indonesia-Jawa Kuno (1992)-hasil-ekstraksi.csv,13,3312,9.59,172
8,67. Kamus Aceh Indonesia (A-L) (1985)-hasil-ekstraksi.csv,112,48446,9.66,560
9,74. Kamus Bahasa Melayu Bangka-Indonesia (2018)-hasil-ekstraksi.csv,3627,0,11.98,156
10,79. Kamus Bahasa Jawa-Bahasa Indonesia II (1993)-hasil-ekstraksi.csv,13,7670,10.89,415
11,84. Kamus Bahasa Biak - Indonesia (1977) -hasil-ekstraksi.csv,1,9565,8.33,79
12,94. Kamus Bahasa Madura-Indonesia (1977)-hasil-ekstraksi.csv,126,14027,7.90,208