In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

In [2]:
# directory = "[Full] CSV JSON all information"
directory = '/Users/rafaeldewandaru/SEMESTER 8/Tugas Akhir/TAEkstraksiKamus/[Full] CSV JSON all information - Final'

In [3]:
def count_font_bold(data):
    cnt = 0
    for i in data:
        if "bold" in i.lower():
            cnt += 1
    return cnt

def count_font_italic(data):
    cnt = 0
    for i in data:
        if "italic" in i.lower():
            cnt += 1
    return cnt

In [4]:
page = [1,1,1,1,2,2,2,2,]

page = np.array(page)
page = np.unique(page)
page[-1]

np.int64(2)

In [5]:
result = {
    "nama_kamus":[],
    "jumlah_bold":[],
    "jumlah_italic":[],
    "mean_ukuran_char":[],
    "banyak_halaman":[]
}

for filename in tqdm(os.listdir(directory)):
    data = pd.read_csv(directory + "/" + filename)
    
    sum_bold = count_font_bold(data["font"].values.tolist())
    sum_italic = count_font_italic(data["font"].values.tolist())
    
    size = data["size"].values.tolist()

    page = np.array(data["page"].values.tolist())
    page = np.unique(page)
    
    result['nama_kamus'].append(filename)
    result['jumlah_bold'].append(sum_bold)
    result['jumlah_italic'].append(sum_italic)
    result['mean_ukuran_char'].append(round(np.mean(size),2))
    result['banyak_halaman'].append(len(page))

100%|██████████| 58/58 [00:02<00:00, 28.87it/s]

In [6]:
pandas_res = pd.DataFrame.from_dict(result)
# tampilkan seluruh baris dan seluruh nilai pada kolom
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(pandas_res)

# reset option
pd.reset_option("display")

pandas_res.to_csv(directory + "/exploratory_kamus_analysis.csv",index=False)

,nama_kamus,jumlah_bold,jumlah_italic,mean_ukuran_char,banyak_halaman
0,27. Kamus Bahasa Indonesia-Saluan (2012)-hasil-ekstraksi.csv,9105,11147,10.10,120
1,63. Kamus Bahasa Indonesia-Lampung Dialek A (1999)-hasil-ekstraksi.csv,972,13724,10.77,321
2,13. Kamus Bahasa Indonesia-Bahasa Sunda I (1993)-hasil-ekstraksi.csv,317,22602,10.55,408
3,50. Kamus Indonesia-Jawa Kuno (1992)-hasil-ekstraksi.csv,13,3312,9.59,172
4,56. Kamus Lampung-Indonesia (1985)-hasil-ekstraksi.csv,6144,27041,10.24,305
5,42. Kamus Bahasa Indonesia-Bahasa Sunda II (1993)-hasil-ekstraksi.csv,6365,35806,11.32,486
6,10. Kamus Bahasa Indonesia-Dayak Deah Edisi I (2013)-hasil-ekstraksi.csv,5634,17598,9.07,300
7,33. Kamus Wolio Indonesia (1985)-hasil-ekstraksi.csv,2746,12779,10.27,191
8,51. Kamus Bahasa Bali Kuno-Indonesia (1985)-hasil-ekstraksi.csv,1911,5688,9.95,122
9,17. Kamus Melayu Makasar-Indonesia (1985)-hasil-ekstraksi.csv,2838,12798,10.21,143
10,24. Kamus Minangkabau-Indonesia (1985)-hasil-ekstraksi.csv,11952,26256,9.92,312
11,87. Kamus Bahasa Indonesia-Kaidipang (A-K) (1999)-hasil-ekstraksi.csv,878,30146,10.71,525
12,44. Kamus Melayu Deli-Indonesia (1985)-hasil-ekstraksi.csv,2150,8078,10.20,117
13,4. Kamus Bahasa Indonesia-Jambi A-K (1998)-hasil-ekstraksi.csv,4023,23554,11.37,208
14,31. Kamus Sumbawa-Indonesia (1985)-hasil-ekstraksi.csv,483,10553,9.31,167
15,34. Kamus Bahasa Indonesia-Bali L-Z (1998)-hasil-ekstraksi.csv,16323,18825,10.76,498
16,52. Kamus Ogan-Indonesia (1985)-hasil-ekstraksi.csv,6643,21366,10.45,249
17,15. Kamus Bahasa Indonesia-Pasir (1997)-hasil-ekstraksi.csv,673,39746,10.74,529
18,85. Kamus Tondano-Indonesia (1985)-hasil-ekstraksi.csv,1229,16617,9.25,296
19,23. Kamus Dwibahasa Dayak Ngaju-Indonesia (2013)-hasil-ekstraksi.csv,3581,631,8.98,154
20,9. Kamus Manado-Indonesia (1985)-hasil-ekstraksi.csv,8908,10412,9.32,136
21,16. Kamus Bahasa Indonesia Karo A-K (1998)-hasil-ekstraksi.csv,2257,28938,10.36,401
22,19. Kamus Bahasa Indoensia-Melayu Riau (1997)-hasil-ekstraksi.csv,9504,29076,11.55,436
23,12. Kamus Bahasa Indonesia-Kaidipang L-Z (2000)-hasil-ekstraksi.csv,12383,28479,11.15,512
24,78. Kamus Tolaki-Indonesia (1985)-hasil-ekstraksi.csv,179,13280,9.67,160
25,37. Kamus Bahasa Indonesia Bakumpai II (1995)-hasil-ekstraksi.csv,42,22995,10.64,250
26,66. Kamus Melayu Bali-Indonesia (1985)-hasil-ekstraksi.csv,2032,8711,10.21,126
27,74. Kamus Bahasa Melayu Bangka-Indonesia (2018)-hasil-ekstraksi.csv,3627,0,11.98,156
28,91. Kamus Simalungun - Indonesia (edisi kedua) (2015)-hasil-ekstraksi.csv,13465,33758,9.98,264
29,79. Kamus Bahasa Jawa-Bahasa Indonesia II (1993)-hasil-ekstraksi.csv,13,7670,10.89,415
30,20. Kamus Bahasa Melayu Ambon-Indonesia (1998)-hasil-ekstraksi.csv,2230,12638,11.78,138
31,14. Kamus Bahasa Indonesia-Bahasa Minangkabau II (1994)-hasil-ekstraksi.csv,606,30562,10.79,465
32,71. Kamus dwibahasa Bugis-Indonesia (2017)-hasil-ekstraksi.csv,1201,3623,11.02,49
33,28. Kamus Bahasa Kutai-Bahasa Indonesia (2013)-hasil-ekstraksi.csv,819,27928,10.59,436
34,46. Kamus Bahasa Banjar Dialek Hulu-Indonesia (2008)-hasil-ekstraksi.csv,26876,36691,8.52,310
35,2. Kamus Melayu-Indonesia (1985)-hasil-ekstraksi.csv,7563,15196,10.68,229
36,25. Kamus Bahasa Indonesia Jambi L-Z (1997)-hasil-ekstraksi.csv,136,32818,11.26,332
37,68. Kamus Dwibahasa Bahasa Talaud - Bahasa Indonesia (2018)-hasil-ekstraksi.csv,13907,19156,11.02,283
38,18. Kamus Bahasa Jawa-Bahasa Indonesia I (1993)-hasil-ekstraksi.csv,20527,8640,11.11,450
39,36. Kamus Bahasa Indonesia-Kulawi (2012)-hasil-ekstraksi.csv,1443,21190,9.60,222
40,48. Kamus Muna-Indonesia (1985)-hasil-ekstraksi.csv,124,10311,9.78,140
41,11. Kamus Suwawa-Indonesia (1985)-hasil-ekstraksi.csv,4,34930,9.41,335
42,21. Kamus Bahasa Indonesia-Sentani A-K (1999)-hasil-ekstraksi.csv,5104,14987,11.32,182
43,32. Kamus Melayu Langkat-Indonesia (1985)-hasil-ekstraksi.csv,3246,8312,10.05,183
44,67. Kamus Aceh Indonesia (A-L) (1985)-hasil-ekstraksi.csv,112,48446,9.66,560
45,41. Kamus Bahasa Indonesia-Bali A-K (1997)-hasil-ekstraksi.csv,16876,23898,11.50,451
46,29. Kata Tetun Indonesia (1985)-hasil-ekstraksi.csv,3088,12896,10.37,118
47,94. Kamus Bahasa Madura-Indonesia (1977)-hasil-ekstraksi.csv,126,14027,7.90,208
48,3. Kamus Bahasa Gorontalo-Indonesia (2001)-hasil-ekstraksi.csv,62,37205,8.19,302
49,8. Kamus Indonesia-Angkola (1995)-hasil-ekstraksi.csv,310,4417,8.80,154
50,60. Kamus Sunda-Indonesia (1985)-hasil-ekstraksi.csv,480,8381,9.09,382
51,5. Kamus Bahasa Indonesia-Bahasa Tonsea I (1996)-hasil-ekstraksi.csv,4744,2145,11.15,148
52,26. Kamus Bahasa Indonesia-Bahasa Tonsea II (1996)-hasil-ekstraksi.csv,5354,2711,11.09,168
53,58. Kamus Melayu Ketapang-Indonesia A-M (2010)-hasil-ekstraksi.csv,5849,1723,9.46,159
54,22. Kamus Bahasa Gorontalo-Indonesia (1977)-hasil-ekstraksi.csv,37,37556,8.42,302
55,84. Kamus Bahasa Biak - Indonesia (1977) -hasil-ekstraksi.csv,1,9565,8.33,79
56,38. Kamus Bahasa Indonesia-Karo L-Z (1999)-hasil-ekstraksi.csv,2113,30006,10.86,584
57,55. Kamus Bahasa Indonesia Bakumpai I (1995)-hasil-ekstraksi.csv,2334,19643,11.29,198

In [7]:
pandas_res = pd.read_csv(directory + "/exploratory_kamus_analysis.csv")

pandas_res = pandas_res[(pandas_res["jumlah_bold"] >= pandas_res["banyak_halaman"]) & (pandas_res["jumlah_italic"] >= pandas_res["banyak_halaman"])]
pandas_res = pandas_res.reset_index(drop=True)
# tampilkan seluruh baris dan seluruh nilai pada kolom
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pandas_res.to_csv("daftar_kamus_ekstraks.csv",index=False)

display(pandas_res)

# reset option
pd.reset_option("display")

,nama_kamus,jumlah_bold,jumlah_italic,mean_ukuran_char,banyak_halaman
0,27. Kamus Bahasa Indonesia-Saluan (2012)-hasil-ekstraksi.csv,9105,11147,10.10,120
1,63. Kamus Bahasa Indonesia-Lampung Dialek A (1999)-hasil-ekstraksi.csv,972,13724,10.77,321
2,56. Kamus Lampung-Indonesia (1985)-hasil-ekstraksi.csv,6144,27041,10.24,305
3,42. Kamus Bahasa Indonesia-Bahasa Sunda II (1993)-hasil-ekstraksi.csv,6365,35806,11.32,486
4,10. Kamus Bahasa Indonesia-Dayak Deah Edisi I (2013)-hasil-ekstraksi.csv,5634,17598,9.07,300
5,33. Kamus Wolio Indonesia (1985)-hasil-ekstraksi.csv,2746,12779,10.27,191
6,51. Kamus Bahasa Bali Kuno-Indonesia (1985)-hasil-ekstraksi.csv,1911,5688,9.95,122
7,17. Kamus Melayu Makasar-Indonesia (1985)-hasil-ekstraksi.csv,2838,12798,10.21,143
8,24. Kamus Minangkabau-Indonesia (1985)-hasil-ekstraksi.csv,11952,26256,9.92,312
9,87. Kamus Bahasa Indonesia-Kaidipang (A-K) (1999)-hasil-ekstraksi.csv,878,30146,10.71,525
10,44. Kamus Melayu Deli-Indonesia (1985)-hasil-ekstraksi.csv,2150,8078,10.20,117
11,4. Kamus Bahasa Indonesia-Jambi A-K (1998)-hasil-ekstraksi.csv,4023,23554,11.37,208
12,31. Kamus Sumbawa-Indonesia (1985)-hasil-ekstraksi.csv,483,10553,9.31,167
13,34. Kamus Bahasa Indonesia-Bali L-Z (1998)-hasil-ekstraksi.csv,16323,18825,10.76,498
14,52. Kamus Ogan-Indonesia (1985)-hasil-ekstraksi.csv,6643,21366,10.45,249
15,15. Kamus Bahasa Indonesia-Pasir (1997)-hasil-ekstraksi.csv,673,39746,10.74,529
16,85. Kamus Tondano-Indonesia (1985)-hasil-ekstraksi.csv,1229,16617,9.25,296
17,23. Kamus Dwibahasa Dayak Ngaju-Indonesia (2013)-hasil-ekstraksi.csv,3581,631,8.98,154
18,9. Kamus Manado-Indonesia (1985)-hasil-ekstraksi.csv,8908,10412,9.32,136
19,16. Kamus Bahasa Indonesia Karo A-K (1998)-hasil-ekstraksi.csv,2257,28938,10.36,401
20,19. Kamus Bahasa Indoensia-Melayu Riau (1997)-hasil-ekstraksi.csv,9504,29076,11.55,436
21,12. Kamus Bahasa Indonesia-Kaidipang L-Z (2000)-hasil-ekstraksi.csv,12383,28479,11.15,512
22,78. Kamus Tolaki-Indonesia (1985)-hasil-ekstraksi.csv,179,13280,9.67,160
23,66. Kamus Melayu Bali-Indonesia (1985)-hasil-ekstraksi.csv,2032,8711,10.21,126
24,91. Kamus Simalungun - Indonesia (edisi kedua) (2015)-hasil-ekstraksi.csv,13465,33758,9.98,264
25,20. Kamus Bahasa Melayu Ambon-Indonesia (1998)-hasil-ekstraksi.csv,2230,12638,11.78,138
26,14. Kamus Bahasa Indonesia-Bahasa Minangkabau II (1994)-hasil-ekstraksi.csv,606,30562,10.79,465
27,71. Kamus dwibahasa Bugis-Indonesia (2017)-hasil-ekstraksi.csv,1201,3623,11.02,49
28,28. Kamus Bahasa Kutai-Bahasa Indonesia (2013)-hasil-ekstraksi.csv,819,27928,10.59,436
29,46. Kamus Bahasa Banjar Dialek Hulu-Indonesia (2008)-hasil-ekstraksi.csv,26876,36691,8.52,310
30,2. Kamus Melayu-Indonesia (1985)-hasil-ekstraksi.csv,7563,15196,10.68,229
31,68. Kamus Dwibahasa Bahasa Talaud - Bahasa Indonesia (2018)-hasil-ekstraksi.csv,13907,19156,11.02,283
32,18. Kamus Bahasa Jawa-Bahasa Indonesia I (1993)-hasil-ekstraksi.csv,20527,8640,11.11,450
33,36. Kamus Bahasa Indonesia-Kulawi (2012)-hasil-ekstraksi.csv,1443,21190,9.60,222
34,21. Kamus Bahasa Indonesia-Sentani A-K (1999)-hasil-ekstraksi.csv,5104,14987,11.32,182
35,32. Kamus Melayu Langkat-Indonesia (1985)-hasil-ekstraksi.csv,3246,8312,10.05,183
36,41. Kamus Bahasa Indonesia-Bali A-K (1997)-hasil-ekstraksi.csv,16876,23898,11.50,451
37,29. Kata Tetun Indonesia (1985)-hasil-ekstraksi.csv,3088,12896,10.37,118
38,8. Kamus Indonesia-Angkola (1995)-hasil-ekstraksi.csv,310,4417,8.80,154
39,60. Kamus Sunda-Indonesia (1985)-hasil-ekstraksi.csv,480,8381,9.09,382
40,5. Kamus Bahasa Indonesia-Bahasa Tonsea I (1996)-hasil-ekstraksi.csv,4744,2145,11.15,148
41,26. Kamus Bahasa Indonesia-Bahasa Tonsea II (1996)-hasil-ekstraksi.csv,5354,2711,11.09,168
42,58. Kamus Melayu Ketapang-Indonesia A-M (2010)-hasil-ekstraksi.csv,5849,1723,9.46,159
43,38. Kamus Bahasa Indonesia-Karo L-Z (1999)-hasil-ekstraksi.csv,2113,30006,10.86,584
44,55. Kamus Bahasa Indonesia Bakumpai I (1995)-hasil-ekstraksi.csv,2334,19643,11.29,198

In [8]:
pandas_res = pd.read_csv(directory + "/exploratory_kamus_analysis.csv")

pandas_res = pandas_res[(pandas_res["jumlah_bold"] < pandas_res["banyak_halaman"]) | (pandas_res["jumlah_italic"] < pandas_res["banyak_halaman"])]
pandas_res = pandas_res.reset_index(drop=True)
# tampilkan seluruh baris dan seluruh nilai pada kolom
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(pandas_res)

# reset option
pd.reset_option("display")
pandas_res.to_csv("daftar kamus yang tidak diekstrak.csv",index=False)

,nama_kamus,jumlah_bold,jumlah_italic,mean_ukuran_char,banyak_halaman
0,13. Kamus Bahasa Indonesia-Bahasa Sunda I (1993)-hasil-ekstraksi.csv,317,22602,10.55,408
1,50. Kamus Indonesia-Jawa Kuno (1992)-hasil-ekstraksi.csv,13,3312,9.59,172
2,37. Kamus Bahasa Indonesia Bakumpai II (1995)-hasil-ekstraksi.csv,42,22995,10.64,250
3,74. Kamus Bahasa Melayu Bangka-Indonesia (2018)-hasil-ekstraksi.csv,3627,0,11.98,156
4,79. Kamus Bahasa Jawa-Bahasa Indonesia II (1993)-hasil-ekstraksi.csv,13,7670,10.89,415
5,25. Kamus Bahasa Indonesia Jambi L-Z (1997)-hasil-ekstraksi.csv,136,32818,11.26,332
6,48. Kamus Muna-Indonesia (1985)-hasil-ekstraksi.csv,124,10311,9.78,140
7,11. Kamus Suwawa-Indonesia (1985)-hasil-ekstraksi.csv,4,34930,9.41,335
8,67. Kamus Aceh Indonesia (A-L) (1985)-hasil-ekstraksi.csv,112,48446,9.66,560
9,94. Kamus Bahasa Madura-Indonesia (1977)-hasil-ekstraksi.csv,126,14027,7.90,208
10,3. Kamus Bahasa Gorontalo-Indonesia (2001)-hasil-ekstraksi.csv,62,37205,8.19,302
11,22. Kamus Bahasa Gorontalo-Indonesia (1977)-hasil-ekstraksi.csv,37,37556,8.42,302
12,84. Kamus Bahasa Biak - Indonesia (1977) -hasil-ekstraksi.csv,1,9565,8.33,79